In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("train.csv",delimiter=",")

In [3]:
data.head()

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Y
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,-0.303094,0.410571,-1.097990,37.9
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,0.113032,0.291169,-0.520474,21.4
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,0.806576,-3.795795,0.891076,12.7
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,0.806576,-0.066050,0.215438,19.9
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,0.020560,0.431074,0.029007,22.5

In [4]:
Y=data[' Y']
del data[' Y']
data

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,-0.303094,0.410571,-1.097990
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,0.113032,0.291169,-0.520474
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,0.806576,-3.795795,0.891076
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,0.806576,-0.066050,0.215438
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,0.020560,0.431074,0.029007
...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,-0.204929,-0.487722,1.231945,3.668398,0.434551,2.161728,1.053485,-0.833960,-0.523001,-0.031105,-1.736418,0.361122,-1.504494
375,0.231398,-0.487722,1.015999,-0.272599,1.367490,0.215644,0.687212,-0.703186,1.661245,1.530926,0.806576,-2.812183,0.499991
376,-0.408311,-0.487722,0.247057,-0.272599,-1.016689,-0.206055,-0.809889,0.140451,-0.523001,-0.060801,0.113032,0.332066,-0.334043
377,-0.410620,-0.487722,-1.152214,-0.272599,-0.818007,0.068904,-1.826921,0.674814,-0.637962,0.129256,-0.719220,0.203235,-0.744752
378,0.342909,-0.487722,1.015999,3.668398,0.659147,1.041946,1.028593,-1.232462,1.661245,1.530926,0.806576,0.387875,-1.358713

In [5]:
from sklearn import preprocessing

data=preprocessing.scale(data)
data=pd.DataFrame(data)
data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,-0.400981,-0.490427,-1.281492,-0.287849,-0.605917,1.207950,0.814838,-0.505604,-0.784522,-1.297963,-0.322642,0.420280,-1.100955
1,-0.400534,-0.490427,0.207535,-0.287849,-1.047205,-0.030261,-0.891071,0.328940,-0.557982,-0.102675,0.093911,0.302580,-0.531433
2,0.099008,-0.490427,0.964253,-0.287849,1.340946,-0.471970,0.659427,-0.561179,1.594148,1.459945,0.788166,-3.726145,0.860578
3,0.008138,-0.490427,0.964253,-0.287849,1.834151,-0.080131,0.775082,-0.693215,1.594148,1.459945,0.788166,-0.049549,0.194293
4,-0.405257,-0.490427,-0.990005,-0.287849,-0.943373,-0.416400,-0.887456,0.294021,-0.784522,-0.983107,0.001343,0.440491,0.010442

In [6]:
lc=np.ones(data.shape[0])
lc.shape
data['lc']=lc

In [7]:
points=np.array(data)
points.shape

(379, 14)

In [8]:
def step_gradient(points,learning_rate,m):
    m_slope=np.zeros(14)
    M=len(points)
    for i in range(M):
        x=points[i]
        y=Y[i]
        for j in range(14):
            m_slope[j] = m_slope[j]+(-2/M)* (y - (m * x).sum() )*x[j]
    
    for j in range(14):
        m[j]=m[j]-learning_rate*m_slope[j]
        
    return m

In [9]:
def gd(points,learning_rate,num_iterations):
    m=np.zeros(14)
    for i in range(num_iterations):
        m=step_gradient(points,learning_rate,m)
        print(i,"Cost: ",cost(points,m))
    return m

In [10]:
def cost(points,m):
    total_cost=0
    M=len(points)
    
    for i in range(M):
        x=points[i]
        y=Y[i];
        total_cost += (1/M)*((y - (m*x).sum() )**2)
    return total_cost

In [23]:
def run():
    learning_rate=0.05
    num_iterations=400
    m=gd(points,learning_rate,num_iterations)
    
    print (m)
    return m

In [24]:
m=run()
m

0 Cost:  469.02446650514304
1 Cost:  380.9298950563564
2 Cost:  312.42403246056386
3 Cost:  257.49642447661637
4 Cost:  213.176988516218
5 Cost:  177.36391607764398
6 Cost:  148.40873249781293
7 Cost:  124.98958743086315
8 Cost:  106.04159079877762
9 Cost:  90.70584175442671
10 Cost:  78.28923930110105
11 Cost:  68.23228452370836
12 Cost:  60.083193063818904
13 Cost:  53.477058144362545
14 Cost:  48.11906882274004
15 Cost:  43.770987933478295
16 Cost:  40.2402520188758
17 Cost:  37.3711814751443
18 Cost:  35.03788988331174
19 Cost:  33.13856218594672
20 Cost:  31.590836061308536
21 Cost:  30.32807274985738
22 Cost:  29.29634526193516
23 Cost:  28.45200537832297
24 Cost:  27.759717773901304
25 Cost:  27.190871248143733
26 Cost:  26.722294473696603
27 Cost:  26.335217707477128
28 Cost:  26.014433213796533
29 Cost:  25.747616260160655
30 Cost:  25.524775892227115
31 Cost:  25.33781061906746
32 Cost:  25.18014891991794
33 Cost:  25.046458341329696
34 Cost:  24.93241006788519
35 Cost:  24.834488364379233
36 Cost:  24.749836318473598
37 Cost:  24.67613095370339
38 Cost:  24.611482108593638
39 Cost:  24.55435054920919
40 Cost:  24.503481648649174
41 Cost:  24.45785166728313
42 Cost:  24.416624233778546
43 Cost:  24.37911508490524
44 Cost:  24.344763492492284
45 Cost:  24.31310910553291
46 Cost:  24.28377317783034
47 Cost:  24.256443347708604
48 Cost:  24.230861295017185
49 Cost:  24.206812729098992
50 Cost:  24.184119265343003
51 Cost:  24.16263183208644
52 Cost:  24.142225317744206
53 Cost:  24.122794223185835
54 Cost:  24.10424912902626
55 Cost:  24.0865138236441
56 Cost:  24.06952296701461
57 Cost:  24.053220189148412
58 Cost:  24.037556541125046
59 Cost:  24.02248923226044
60 Cost:  24.00798059954136
61 Cost:  23.99399726566256
62 Cost:  23.980509450268478
63 Cost:  23.967490405696587
64 Cost:  23.954915953946095
65 Cost:  23.942764105992197
66 Cost:  23.931014748128984
67 Cost:  23.91964938291224
68 Cost:  23.908650914613787
69 Cost:  23.898003470996255
70 Cost:  23.887692254757287
71 Cost:  23.877703419236855
72 Cost:  23.868023963996226
73 Cost:  23.85864164669486
74 Cost:  23.849544908360016
75 Cost:  23.840722809681576
76 Cost:  23.83216497640489
77 Cost:  23.823861552249657
78 Cost:  23.81580315807179
79 Cost:  23.807980856221178
80 Cost:  23.800386119237107
81 Cost:  23.793010802180525
82 Cost:  23.785847118026926
83 Cost:  23.778887615647246
84 Cost:  23.77212515998712
85 Cost:  23.765552914123766
86 Cost:  23.759164322935163
87 Cost:  23.752953098160575
88 Cost:  23.746913204670417
89 Cost:  23.741038847792314
90 Cost:  23.735324461565448
91 Cost:  23.72976469781608
92 Cost:  23.724354415963248
93 Cost:  23.719088673478243
94 Cost:  23.713962716931764
95 Cost:  23.708971973573323
96 Cost:  23.704112043394048
97 Cost:  23.69937869163176
98 Cost:  23.694767841680935
99 Cost:  23.690275568377174
100 Cost:  23.68589809162652
101 Cost:  23.681631770356045
102 Cost:  23.677473096762945
103 Cost:  23.673418690842556
104 Cost:  23.669465295177456
105 Cost:  23.66560976997115
106 Cost:  23.661849088312668
107 Cost:  23.658180331657324
108 Cost:  23.65460068551237
109 Cost:  23.651107435316117
110 Cost:  23.64769796249953
111 Cost:  23.644369740721306
112 Cost:  23.641120332266908
113 Cost:  23.6379473846038
114 Cost:  23.63484862708412
115 Cost:  23.631821867788673
116 Cost:  23.628864990504333
117 Cost:  23.62597595182882
118 Cost:  23.62315277839723
119 Cost:  23.620393564223534
120 Cost:  23.61769646815271
121 Cost:  23.61505971141787
122 Cost:  23.612481575297608
123 Cost:  23.609960398869166
124 Cost:  23.607494576852858
125 Cost:  23.605082557544026
126 Cost:  23.602722840828207
127 Cost:  23.600413976276112
128 Cost:  23.59815456131488
129 Cost:  23.59594323947215
130 Cost:  23.59377869869001
131 Cost:  23.59165966970538
132 Cost:  23.589584924494588
133 Cost:  23.58755327477883
134 Cost:  23.58556357058834
135 Cost:  23.583614698882347
136 Cost:  23.58170558222291
137 Cost:  23.579835177500303
138 Cost:  23.578002474707194
139 Cost:  23.576206495760676
140 Cost:  23.574446293369043
141 Cost:  23.57272094994237
142 Cost:  23.571029576544326
143 Cost:  23.569371311884304
144 Cost:  23.567745321347516
145 Cost:  23.566150796061912
146 Cost:  23.564586952000454
147 Cost:  23.5630530291171
148 Cost:  23.561548290515226
149 Cost:  23.560072021647166
150 Cost:  23.558623529543887
151 Cost:  23.557202142073148
152 Cost:  23.55580720722528
153 Cost:  23.55443809242553
154 Cost:  23.55309418387185
155 Cost:  23.551774885896926
156 Cost:  23.55047962035401
157 Cost:  23.549207826024922
158 Cost:  23.547958958050227
159 Cost:  23.54673248737967
160 Cost:  23.54552790024317
161 Cost:  23.544344697640586
162 Cost:  23.54318239485054
163 Cost:  23.542040520956345
164 Cost:  23.54091861838981
165 Cost:  23.53981624249079
166 Cost:  23.53873296108306
167 Cost:  23.537668354065243
168 Cost:  23.53662201301618
169 Cost:  23.535593540814876
170 Cost:  23.534582551273466
171 Cost:  23.533588668783523
172 Cost:  23.532611527974893
173 Cost:  23.531650773386463
174 Cost:  23.530706059148766
175 Cost:  23.52977704867762
176 Cost:  23.528863414378478
177 Cost:  23.52796483736137
178 Cost:  23.527081007165673
179 Cost:  23.526211621494454
180 Cost:  23.525356385958126
181 Cost:  23.524515013827127
182 Cost:  23.523687225792944
183 Cost:  23.522872749737665
184 Cost:  23.52207132051116
185 Cost:  23.521282679716325
186 Cost:  23.520506575501432
187 Cost:  23.519742762359655
188 Cost:  23.518991000935596
189 Cost:  23.51825105783805
190 Cost:  23.517522705459744
191 Cost:  23.516805721802555
192 Cost:  23.516099890309103
193 Cost:  23.515404999699932
194 Cost:  23.514720843815887
195 Cost:  23.514047221466296
196 Cost:  23.513383936281905
197 Cost:  23.512730796572793
198 Cost:  23.51208761519112
199 Cost:  23.511454209398362
200 Cost:  23.510830400737017
201 Cost:  23.510216014906533
202 Cost:  23.509610881643304
203 Cost:  23.50901483460473
204 Cost:  23.508427711257003
205 Cost:  23.50784935276656
206 Cost:  23.507279603895174
207 Cost:  23.506718312898403
208 Cost:  23.506165331427407
209 Cost:  23.50562051443383
210 Cost:  23.50508372007783
211 Cost:  23.50455480963929
212 Cost:  23.504033647431346
213 Cost:  23.50352010071738
214 Cost:  23.503014039630056
215 Cost:  23.50251533709337
216 Cost:  23.502023868746896
217 Cost:  23.50153951287265
218 Cost:  23.501062150324223
219 Cost:  23.50059166445782
220 Cost:  23.50012794106607
221 Cost:  23.499670868313526
222 Cost:  23.499220336674064
223 Cost:  23.498776238870573
224 Cost:  23.498338469816353
225 Cost:  23.497906926558223
226 Cost:  23.497481508221604
227 Cost:  23.497062115957146
228 Cost:  23.496648652889046
229 Cost:  23.496241024064876
230 Cost:  23.495839136406943
231 Cost:  23.49544289866539
232 Cost:  23.495052221372227
233 Cost:  23.494667016797166
234 Cost:  23.4942871989046
235 Cost:  23.493912683311933
236 Cost:  23.493543387249016
237 Cost:  23.49317922951907
238 Cost:  23.4928201304603
239 Cost:  23.49246601190932
240 Cost:  23.49211679716491
241 Cost:  23.49177241095343
242 Cost:  23.49143277939472
243 Cost:  23.491097829969675
244 Cost:  23.49076749148796
245 Cost:  23.49044169405718
246 Cost:  23.490120369052956
247 Cost:  23.489803449089447
248 Cost:  23.489490867991154
249 Cost:  23.489182560765187
250 Cost:  23.48887846357461
251 Cost:  23.488578513712408
252 Cost:  23.48828264957579
253 Cost:  23.487990810642106
254 Cost:  23.4877029374446
255 Cost:  23.487418971549168
256 Cost:  23.48713885553175
257 Cost:  23.486862532956437
258 Cost:  23.486589948353814
259 Cost:  23.48632104720033
260 Cost:  23.486055775897963
261 Cost:  23.485794081754523
262 Cost:  23.48553591296439
263 Cost:  23.48528121858994
264 Cost:  23.48502994854323
265 Cost:  23.484782053568416
266 Cost:  23.484537485224433
267 Cost:  23.484296195868183
268 Cost:  23.484058138638304
269 Cost:  23.483823267439135
270 Cost:  23.483591536925157
271 Cost:  23.483362902486025
272 Cost:  23.483137320231737
273 Cost:  23.482914746978157
274 Cost:  23.48269514023331
275 Cost:  23.482478458183458
276 Cost:  23.482264659679977
277 Cost:  23.4820537042262
278 Cost:  23.481845551964987
279 Cost:  23.481640163666178
280 Cost:  23.4814375007147
281 Cost:  23.481237525098745
282 Cost:  23.481040199398336
283 Cost:  23.480845486774164
284 Cost:  23.480653350956594
285 Cost:  23.48046375623508
286 Cost:  23.48027666744774

287 Cost:  23.48009204997123
288 Cost:  23.479909869710777
289 Cost:  23.4797300930905
290 Cost:  23.479552687043988
291 Cost:  23.479377619005053
292 Cost:  23.47920485689859
293 Cost:  23.47903436913192
294 Cost:  23.47886612458608
295 Cost:  23.478700092607355
296 Cost:  23.478536242999134
297 Cost:  23.478374546013825
298 Cost:  23.4782149723449
299 Cost:  23.47805749311922
300 Cost:  23.477902079889702
301 Cost:  23.47774870462765
302 Cost:  23.477597339715714
303 Cost:  23.47744795794083
304 Cost:  23.47730053248731
305 Cost:  23.477155036930068
306 Cost:  23.477011445228033
307 Cost:  23.476869731717684
308 Cost:  23.476729871106695
309 Cost:  23.47659183846778
310 Cost:  23.476455609232563
311 Cost:  23.476321159185726
312 Cost:  23.476188464458986
313 Cost:  23.476057501525723
314 Cost:  23.475928247195082
315 Cost:  23.47580067860661
316 Cost:  23.475674773224974
317 Cost:  23.47555050883465
318 Cost:  23.47542786353465
319 Cost:  23.475306815733703
320 Cost:  23.4751873441451
321 Cost:  23.475069427781992
322 Cost:  23.474953045952507
323 Cost:  23.474838178255194
324 Cost:  23.474724804574322
325 Cost:  23.474612905075666
326 Cost:  23.4745024602017
327 Cost:  23.474393450667595
328 Cost:  23.474285857456803
329 Cost:  23.47417966181711
330 Cost:  23.474074845256318
331 Cost:  23.473971389538352
332 Cost:  23.473869276679395
333 Cost:  23.473768488943943
334 Cost:  23.47366900884101
335 Cost:  23.47357081912046
336 Cost:  23.473473902769374
337 Cost:  23.47337824300842
338 Cost:  23.473283823288345
339 Cost:  23.47319062728652
340 Cost:  23.473098638903622
341 Cost:  23.473007842260134
342 Cost:  23.472918221693234
343 Cost:  23.47282976175349
344 Cost:  23.472742447201735
345 Cost:  23.47265626300594
346 Cost:  23.4725711943382
347 Cost:  23.47248722657167
348 Cost:  23.472404345277656
349 Cost:  23.472322536222723
350 Cost:  23.47224178536588
351 Cost:  23.472162078855643
352 Cost:  23.472083403027487
353 Cost:  23.472005744400946
354 Cost:  23.471929089677086
355 Cost:  23.47185342573579
356 Cost:  23.471778739633297
357 Cost:  23.47170501859961
358 Cost:  23.471632250035892
359 Cost:  23.47156042151225
360 Cost:  23.471489520765182
361 Cost:  23.471419535695187
362 Cost:  23.471350454364543
363 Cost:  23.47128226499489
364 Cost:  23.47121495596505
365 Cost:  23.471148515808835
366 Cost:  23.47108293321278
367 Cost:  23.471018197013986
368 Cost:  23.47095429619816
369 Cost:  23.47089121989731
370 Cost:  23.47082895738785
371 Cost:  23.470767498088563
372 Cost:  23.47070683155861
373 Cost:  23.470646947495425
374 Cost:  23.470587835733074
375 Cost:  23.470529486240082
376 Cost:  23.470471889117785
377 Cost:  23.470415034598318
378 Cost:  23.470358913042947
379 Cost:  23.47030351494026
380 Cost:  23.47024883090425
381 Cost:  23.470194851672822
382 Cost:  23.470141568105916
383 Cost:  23.470088971183966
384 Cost:  23.47003705200617
385 Cost:  23.469985801788805
386 Cost:  23.469935211863795
387 Cost:  23.46988527367701
388 Cost:  23.46983597878667
389 Cost:  23.469787318861936
390 Cost:  23.469739285681364
391 Cost:  23.46969187113136
392 Cost:  23.46964506720479
393 Cost:  23.469598865999473
394 Cost:  23.469553259716825
395 Cost:  23.469508240660396
396 Cost:  23.469463801234493
397 Cost:  23.469419933942902
398 Cost:  23.46937663138743
399 Cost:  23.46933388626668
[-0.99122598  0.71803033 -0.05335228  0.82546053 -2.16007049  2.36167544
  0.11453358 -3.03290589  2.43189761 -1.57186152 -2.24372241  0.59410817
 -4.32025375 22.60949868]

array([-0.99122598,  0.71803033, -0.05335228,  0.82546053, -2.16007049,
        2.36167544,  0.11453358, -3.03290589,  2.43189761, -1.57186152,
       -2.24372241,  0.59410817, -4.32025375, 22.60949868])

In [26]:
def predict(X_test,m):
    z=m*X_test
    y_pred=z.sum(axis=1)
    return y_pred

In [27]:
X_test=pd.read_csv("test.csv",delimiter=",",dtype="float32")

In [28]:
lc=np.ones(X_test.shape[0])
X_test['lc']=lc

X_test.dtypes

Unnamed:0     float32
Unnamed:1     float32
Unnamed:2     float32
Unnamed:3     float32
Unnamed:4     float32
Unnamed:5     float32
Unnamed:6     float32
Unnamed:7     float32
Unnamed:8     float32
Unnamed:9     float32
Unnamed:10    float32
Unnamed:11    float32
Unnamed:12    float32
lc            float64
dtype: object

In [29]:

y_predict=predict(X_test,m)

y_predict

0      12.182428
1      28.894201
2      22.407297
3      24.310021
4      20.659527
         ...
122    23.068673
123    24.853192
124    17.283935
125    20.800551
126    14.678756
Length: 127, dtype: float64